### ISSUE TITLE
logf: loggers.KV

### ISSUE THREAD

**Issue by jnichols-git** [decentplatforms/appkit#11]
With KV logging implemented, there should be a default KV logger the same way the other formats have in `package loggers`. Rather than having individual parameters, accept a `formats.KVConfig` as the first argument, and update the other default loggers to do the same.

**Comment by nhAnik** [comment]
Hi @jakenichols2719 , can I give it a try?

**Comment by jnichols-git** [comment]
@nhAnik Sure thing! Assigning now.
